kind: Service
apiVersion: v1
metadata:
  name:  mynginxservice
  namespace: test
spec:
  selector:
   app: nginx
  type: ClusterIP
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort:  80
# ClusterIP: 
# NodePort:
# LoadBalancer: offering by cloud providers