apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
  namespace: dev
  labels:
    app: nginx
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:perl
          resources:
            limits:
              memory: "64Mi"
              cpu: "50m"
          imagePullPolicy: IfNotPresent
          ports:
          - name: default
            containerPort: 80
