apiVersion: v1
kind: Pod
metadata:
  name: mynginx1
  namespace: test
  labels:
    app: nginx
spec:
  containers:
  - name: mynginx-container1
    image: nginx
  - name: mynginx-container2
    image: nginx123
    ports:
      - containerPort: 80
