apiVersion: v1
kind: Service
metadata:
 name: nginx-headless
 namespace: dev
spec:
  clusterIP: None # This creates a headless service
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
  namespace: dev
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx-headless
  replicas: 10
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: ngnix
        image: nginx-headless
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html # the path inside the pod/container
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      name: nginx-pv
      accessModes: [ "ReadWriteOnce" ] # only one node can read and write to the volume.
      resources:
        requests:
          storage: 1Gi
  # CSI -> Container Storage Interface --> Minikube CSI
  # CNI -> Container Netwroking Interface -->Kube-Network
  # CRI -> Container Runtime Interface --> Docker Container Runtime
