apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap1
  namespace: dev
data:
  APP_PORT: "8081"
---
apiVersion: v1
kind: Pod
metadata:
  name: example-pod1
  namespace: dev
spec:
  restartPolicy: Never
  containers:
    - name: example-container1
      image: busybox
      command: ['sh', '-c','echo The app port is $APP_PORT']
      env:
      - name: APP_PORT
        #value: "8081"
        valueFrom:
          configMapKeyRef:
            name: demo-configmap1
            key: APP_PORT