apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret1
  namespace: dev
type: Opaque
data:
  password: aml0ZW5AMTIzCg==
---
apiVersion: v1
kind: Pod
metadata:
  name: example-pod1
  namespace: dev
spec:
  restartPolicy: Never
  containers:
  - name: example-container1
    image: busybox
    command: ["sh","-c",'echo Hello This is the password:$MY_PASSDWORD']
    env:
     - name: MY_PASSDWORD
       valueFrom:
          secretKeyRef:
            name: example-secret1
            key: password
