apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config1
  namespace: dev
data:
  app-port: "8081"
---
apiVersion: v1
kind: Pod
metadata:
  name: example-pod1
  namespace: dev
spec:
  containers:
  - name: example-container1
    image: busybox
    command: ['sh', '-c', 'echo $MY_VAR && sleep 3600']
    env:
    - name: MY_VAR
      valueFrom:
        configMapKeyRef:
          name: demo-config
          key: app-port