apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config2
  namespace: dev
data:
  APP_PORT: "8081"
  APP_TYPE: "Backend"
---
apiVersion: v1
kind: Pod
metadata:
  name: example-pod2
  namespace: dev
spec:
  containers:
  - name: example-container2
    image: busybox
    command: ['sh', '-c', 'env']
    envFrom:
     - configMapRef:
        name: demo-config2
