apiVersion: v1
kind: Pod
metadata:
  labels:
    app: uploadapp
spec:
  containers:
  - name: uploadapp
    image: jpalaparthi/hitachi_upload_app:v02
    ports:
    - containerPort: 8081
        name: web
      volumeMounts:
      - name: temp-storage
        mountPath: /uploads # it gets mounted inside the path of teh container
    volumes:
      - name: temp-storage
        emptyDir: {}